version: '3.8'

services:
  php: 
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
      
  db: 
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: vidaSerena
    ports:
      - "3307:3306"
    volumes:
      - ./src/SQL:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge